import { Inter } from 'next/font/google'
import AuthProvider, { NextUiProvider } from '@/providers/Providers'

import './globals.css'
import { AppProvider } from '@/context/AppContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Maxim Tiempos',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NextUiProvider>
            <AppProvider>
              {children}
            </AppProvider>
          </NextUiProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
